[package]
name = "respite"
version = "0.1.0"
edition = "2021"
description = "An async reader for RESP streams"
homepage = "https://github.com/braddunbar/respite"
license-file = "LICENSE"
readme = "README.md"
exclude = [
  "ci",
]

[dependencies]
async-recursion = "1.0.5"
bytes = "1.5.0"
ordered-float = "4.2.0"
thiserror = "1.0.56"
triomphe = "0.1.11"

[dependencies.tokio]
version = "1.35.1"
features = [
  "io-util",
  "macros",
  "rt",
]
