name: CI

on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: sh ci/check.sh
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: sh ci/test.sh
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
